package edu.duke.cs.osprey.sparse;

import java.util.ArrayList;
import java.util.List;
import edu.duke.cs.osprey.confspace.ConfSpace;
import edu.duke.cs.osprey.confspace.RCTuple;
import edu.duke.cs.osprey.confspace.SearchProblem;
import edu.duke.cs.osprey.energy.EnergyFunction;

/**
 * This class is a container for the branch-decomposition and the corresponding subproblems 
 * generated by said branch-decomposition.
 * @author JJ
 *
 */
public class BranchDecomposedProblem {
	Subproblem root;
	TreeNode sparseTree;
	PartialConformationEnergyFunction sparseEnergyFunction;
	
	public BranchDecomposedProblem(SearchProblem problem, EnergyFunction eFunc)
	{
		sparseEnergyFunction = new PartialConformationEnergyFunction(eFunc, problem.confSpace);
		buildDecomposedProblem(sparseTree, problem.confSpace);
	}
	
	public void preprocess()
	{
		root.preprocess();
	}
	
	public void buildDecomposedProblem(TreeNode sparseTree, ConfSpace superSpace)
	{
		RCTuple emptyConf = new RCTuple();
		root = new Subproblem(superSpace, sparseTree, emptyConf);
	}
	

}
