package edu.duke.cs.osprey.sparse;

/**
 * This class is a container for the branch-decomposition and the corresponding subproblems 
 * generated by said branch-decomposition.
 * @author JJ
 *
 */
public class BranchDecomposedProblem {
	Subproblem root;

}
